### ISSUE TITLE
Enable decryption for custom PrivateKey implementations

### ISSUE THREAD

**Issue by indygreg** [RustCrypto/RSA#159] opened 2022-04-24 02:17 UTC
Thank you for this terrific crate!

I'm attempting to implement RSA decryption using a YubiKey. The YubiKey PIV API only appears to do the low-level RSA decryption, what this crate appears to expose as `rsa::raw::DecryptionPrimitive`.

This means that we need to handle padding ourselves.

(I had to implement EMSA-PKCS1-v1_5 padding myself in order to produce cryptographic signatures using the YubiKey. It is... annoying having to work at a lower level than what many cryptography libraries deem _safe_. I end up implementing my own crypto, which scares me.)

This crate has implemented all of the code to do what I need to do. But as far as I can tell the public APIs aren't there. For this crate to satisfy my use case, I _think_ one of the following 2 things needs to happen:

a) `rsa::raw::DecryptionPrimitive` would need to be exposed. (It is marked as `public` but there isn't a way to get a handle on it AFAICT since its module isn't `public`.)
b) The low level padding-aware decryption functions would need to be exposed. e.g. `rsa::oaep::decrypt_inner()`. However, this would need to be done in such a way that they don't depend on non-public traits like `rsa::raw::DecryptionPrimitive` so you could actually fully implement `rsa::key::PrivateKey`.

I _think_ the preferred solution here is to expose enough traits that you can delegate the core RSA operations to _something else_, like a YubiKey, HSM, or other PKCS#11 device.

Are you amenable to enabling this use case with this crate? If so, what are next steps? (I'm willing to author PRs.)

**Comment by str4d** [comment] 2022-04-24 07:37
This is a duplicate of https://github.com/RustCrypto/RSA/issues/32, and the `DecryptionPrimitive` trait is precisely one that I created in order to enable this use case for users of the `yubikey` crate (https://github.com/iqlusioninc/yubikey.rs). Indeed, both `DecryptionPrimitive and `rsa::oaep::decrypt` are intended to be accessible in some way (to use in place of `RsaPrivateKey`), but not as part of the default crate interface. Let's move this discussion back to that issue.

**Closed by str4d** 2022-04-24 07:37 UTC

**Comment by indygreg** [comment] 2022-04-25 06:02
Ahh, I somehow missed this older issue in my search before filing this one. Sorry about that!

I agree this one is a dupe.
