### ISSUE TITLE
Slow key generation

### ISSUE THREAD

**Issue by kaimast** [RustCrypto/RSA#29] opened 2019-09-29 19:26 UTC
Hi all,

I have the following code snippet. 

```rust
use rsa::RSAPrivateKey;
use rand::thread_rng;

let mut rng = thread_rng();
let private = RSAPrivateKey::new(&mut rng, 2048).unwrap();    
```

It sometimes takes about a second to execute, but most of the time it takes tens of seconds. Am I doing something wrong? Is there a different RNG that is faster?

Thanks!

**Comment by r10s** [comment] 2019-09-30 11:30
if you're running with the `--release` flag, things should be faster (typically few seconds).

but if you leave out this flag, things may take some tens of seconds.

at least this is what i've noticed for delta chat.

**Comment by kaimast** [comment] 2019-09-30 20:42
Thanks for the feedback!

I can confirm that it is much faster in release mode. It should not be that slow in with debug symbols enabled though.

Or is this a rust specific problem that debug bulids are much much slower?

**Comment by r10s** [comment] 2019-09-30 21:08
> Thanks for the feedback!

np

> Or is this a rust specific problem that debug bulids are much much slower?

not sure about rust, but eg, e.g https://github.com/deltachat/deltachat-core/issues/376#issuecomment-428734213 we encountered debug encryption being up to 20 times slower than release one - on c with openssl (not sure if this can be tweaked, we switched to rust then ;)

**Comment by newpavlov** [comment] 2019-10-01 06:27
@kaimast 
[`dev`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections) profile uses the lowest optimization level by default, so it's not only debug symbols, i.e. you are measuring performance for binary without any optimizations whatsoever.

**Comment by olback** [comment] 2020-01-28 01:58
I also ran into this problem. Turns out the Rust compiler is SUPER EFFICIENT when compiling a release. Generating a 2048 bit key in debug mode took arround 5 minutes, meanwhile in a release build it takes about 1 second.

**Comment by dignifiedquire** [comment] 2020-04-11 13:28
Closing, as this is expected behaviour

**Closed by dignifiedquire** 2020-04-11 13:28 UTC

**Comment by kaimast** [comment] 2020-05-03 01:43
Would be great to keep this open. Key generation still takes several seconds in release mode for me. Looks like it's at least an order of magnitude slower than that of openssh. I am sure there are ways to improve upon this.
